language: ruby
before_script:
 - cd cents
 - bundle install
script:
  - RAILS_ENV=test bundle exec rake --trace
notifications:
  slack:
    rooms:
      - codepurpose:qBdzNtSLTbE2PbRMftzOSu8d#capstone-notification