# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3acf16e9c744a4f58b0ce987c4c68889f6f1f09685da49657fd533fdcfae4e6b468c11027d8c355eb87a9a2aa134132f7e6e4afa8268ea6cf66fc05ae7f021b

test:
  secret_key_base: 743dfc6cb975a0d4c64c897133c1c8ee98b3749532e4d320598a2a41031bfc623db7fd8d370479fef7da1d250e30aa724df3faec61785e12a8f068256ddd3f1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
